<?php
    /** @var \JaroslawZielinski\TorahVerse\Block\Pick $block */
    $dictaIgnacyLoyolaHtml = $block->getChildHtml('dicta-ignacy-loyola');
?>
<form class="form" id="torahverse-pick" action="#" method="post" autocomplete="off">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= __('Verse Pick:'); ?></span>
        </legend>
        <br>

        <input name="form_key" type="hidden" value="">

        <?php if (!empty($dictaIgnacyLoyolaHtml)): ?>
            <div class="field">
                <label for="dicta" class="label">
                    <span>&nbsp;</span>
                </label>

                <div class="control">
                    <?= $dictaIgnacyLoyolaHtml; ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="field required">
            <label for="siglum" class="label">
                <span><?= __('Siglum'); ?></span>
            </label>

            <div class="control">
                <?= $block->getVersePickComponentHtml(); ?>
            </div>
        </div>
    </fieldset>
</form>
<script type="text/x-magento-init">
    {
        "#torahverse-pick": {
            "validation": {}
        }
    }
</script>
<script>
    require([
        'jquery'
    ], function ($) {
        const ajaxUrl = '/torahverse/siglum/preview',
            resultId = '#preview';
        let dataForm = $('#torahverse-pick');
        $(dataForm).on('submit', function(event) {
            event.preventDefault();
            let validation = dataForm.validation('isValid');
            if (validation) {

            }
        });
    });
</script>
