<?php
    /** @var \JaroslawZielinski\TorahVerse\Block\Pick $block */
    $htmlFormId = $block->getFormHtmlId();
?>
<form class="form" id="<?= $htmlFormId; ?>" action="#" method="post" autocomplete="off">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= __('Verse Pick:'); ?></span>
        </legend>
        <br>

        <input name="form_key" type="hidden" value="">

        <div class="field required">
            <label for="translations" class="label">
                <span><?= __('Siglum'); ?></span>
            </label>
            <div class="control">
                <?= $block->getInputTorahBlockHtml(); ?>
            </div>
        </div>
    </fieldset>
</form>
<script type="text/x-magento-init">
    {
        "#<?= $htmlFormId; ?>": {
            "validation": {}
        }
    }
</script>

<script>
    require([
        'jquery',
        'mage/validation'
    ], function ($) {
        let dataForm = $('#<?= $htmlFormId; ?>');
        $(dataForm).on('submit', function(event) {
            event.preventDefault();
            let validation = dataForm.validation('isValid');
            if (validation) {}
        });
    });
</script>
