<?php
    /** @var \JaroslawZielinski\TorahVerse\Block\Search $block */
    $translations = $block->getTranslations();
?>
<form class="form" id="torahverse-search" action="#" method="post" autocomplete="off">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= __('Torahverse Search'); ?></span>
        </legend>
        <br>
        <div class="field required">
            <label for="translation" class="label">
                <span><?= __('Translation'); ?></span>
            </label>

            <div class="control">
                <select form="torahverse-search" name="translation" id="translation" required="required">
                    <?php foreach ($translations as $translation): ?>
                        <option value="<?= $translation['value']; ?>"><?= $translation['label']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="field required">
            <label for="siglum" class="label">
                <span><?= __('Siglum'); ?></span>
            </label>

            <div class="control">
                <input type="text" name="siglum" id="siglum" value="" title="<?= __('Siglum'); ?>"
                    class="input-text" data-msg-required="<?= __('This is a required field.'); ?>"
                    data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field">
            <label for="preview" class="label">
                <span><?= __('Preview'); ?></span>
            </label>

            <div class="control">
                <textarea form="torahverse-search" name="preview" id="preview" rows="4" cols="50" class="input-text" readonly="readonly"></textarea>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?= __('Preview'); ?>">
                <span><?= __('Preview'); ?></span>
            </button>
        </div>
    </div>

    <?= $block->getChildHtml('html_content'); ?>
</form>
<script type="text/x-magento-init">
    {
        "#torahverse-search": {
            "validation": {}
        }
    }
</script>
<script>
    require([
        'jquery'
    ], function ($) {
        const ajaxUrl = '/torahverse/siglum/preview',
            resultId = '#preview';
        let dataForm = $('#torahverse-search');
        $(dataForm).on('submit', function(event) {
            event.preventDefault();
            let validation = dataForm.validation('isValid');
            if (validation) {
                let translationCode = $('#translation').val(),
                    siglumCode = $('#siglum').val();
                $.ajax({
                    showLoader: false,
                    url: ajaxUrl,
                    data: {
                        isAjax: true,
                        form_key: window.FORM_KEY,
                        translation: translationCode,
                        siglum: siglumCode
                    },
                    type: 'GET',
                    dataType: 'json'
                }).done(function (data) {
                    $(resultId).html(data['result']);
                });
            }
        });
    });
</script>
