<?php
    /** @var \JaroslawZielinski\TorahVerse\Block\Adminhtml\Widget\Slider $block */
    $config = $block->getConfig();
    $customStyles = trim($block->getModuleCustomStyles() ?? '');
    $backgroundHoverColour = $block->getBackgroundHoverColour() ?? 'none';
?>
<?php if ($block->isVisible()): ?>
    <?php if (!empty($customStyles)): ?>
        <style type="text/css">
            /* <![CDATA[ */
            .verse-slider.paused-slider {
                background-color: <?= $backgroundHoverColour; ?>;
            }
            <?= $customStyles; ?>
            /* ]]> */
        </style>
    <?php endif; ?>
    <div class="verse-slider" data-mage-init='{"verseSlider":
        <?=  /* @noEscape */ $block->arrayToJson($config); ?>}'></div>
<?php endif; ?>
