<?php
    /** @var \ITZielArt\TorahVerse\Block\Widget\Slider $block */
    $array = $block->getConfig();
?>
<?php if ($block->isVisible()): ?>
    <div data-mage-init='{"ITZielArt_TorahVerse/js/verseSlider":
        <?=  /* @noEscape */ $block->arrayToJson($block->getConfig()); ?>}'>
        <?php foreach ($block->getItems() as $item): ?>
            <div class="item">
                <?= $item; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
