<?php
    /** @var \JaroslawZielinski\TorahVerse\Block\Adminhtml\Cache\Progress $block */
    $cachedVerses = $block->getCachedVerses();
    $maxVerses = $block->getMaxVerses();
?>
<span><?= $cachedVerses; ?> / <?= $maxVerses; ?></span>
<div class="container">
    <div class="progress">
        <?php
            $progressPercents = $maxVerses > 0
                ? (float)number_format((100 * $cachedVerses) / $maxVerses, 2, '.', '')
                : 0.0;
            $backgroundColor = \JaroslawZielinski\TorahVerse\Helper\Data::getPercentageColor($progressPercents);
        ?>
        <div class="progress-bar" style="width: <?= $progressPercents; ?>%; background-color: <?= $backgroundColor; ?>;"></div>
        <span><?= (int)$progressPercents; ?>%</span>
    </div>
</div>
